meta_data:
  exp_name: "cc_mamujoco_2ant"
  script_path: "run_scripts/train_cc.py"
  num_workers: 1

variables:
constants:
  vae_weight: 0.05
  bc_weight: 4.0
  q_weight: 1.0  # Weight for Q-learning loss
  policy_weight: 0.5  # Weight for policy optimization loss
  diversity_weight: 1.0
  q_lr: 0.000001
  q_pattern_lr: 0.00001
  q_pretrain_steps: 2000
  learning_rate: 0.0002

  # VAE 预训练参数
  vae_pretrain_steps: 1000
  vae_learning_rate: 0.001

  n_steps_per_epoch: 2000 
  n_train_steps: 40000
  batch_size: 256 
  gradient_accumulate_every: 2
  ema_decay: 0.95
  update_ema_every: 1

  # misc
  seed: 10021
  job_name: "{dataset}/hh_{history_horizon}-bcw_{bc_weight}-qw_{q_weight}-pw_{policy_weight}-guidew_{condition_guidance_w}-lr_{learning_rate}-n_ddim_{n_ddim_steps}-{seed}"
  horizon: 1
  returns_scale: 380
  env_type: "mamujoco"
  n_agents: 2
  use_action: True
  discrete_action: False
  decentralized_execution: True
  use_zero_padding: True
  pred_future_padding: True

  # model - use DiffusionBackbone for testing
  model: "models.DiffusionBackbone"
  diffusion: "models.CCDiffusion"
  history_horizon: 30
  n_diffusion_steps: 30
  use_ddim_sample: True
  n_ddim_steps: 3

  returns_condition: True
  predict_epsilon: True
  hidden_dim: 512
  condition_dropout: 0.25
  condition_guidance_w: 2.0
  clip_denoised: True
  renderer: "utils.MAMuJoCoRenderer"

  trajectory_latent_dim: 128
  pattern_latent_dim: 128
  action_latent_dim: 16
  pattern_num_layers: 4
  pattern_dropout: 0.25
  
  # DiffusionBackbone specific parameters
  backbone_layers: 4
  backbone_hidden_dim: 512
  
  # TrajectoryEncoder sequence model parameters
  trajectory_sequence_model: "transformer"  # Options: "transformer", "lstm", "gru"
  trajectory_num_layers: 4
  trajectory_num_heads: 4
  trajectory_dropout: 0.25
  
  use_behavior_cloning: true

  # dataset
  loader: "datasets.VAESequenceDataset"
  normalizer: "CDFNormalizer"
  dataset: "2ant-Good"
  max_n_episodes: 5000
  preprocess_fns: []
  use_padding: True
  discount: 0.95
  max_path_length: 1000
  termination_penalty: 0.0
  include_returns: true
  include_env_ts: true

  # training
  log_freq: 500
  save_freq: 2000
  sample_freq: 0 
  n_saves: 2
  save_parallel: False
  n_reference: 1
  save_checkpoints: True 

  # eval - using VAE evaluator
  evaluator: "utils.VAEDiffusionEvaluator"  # CHANGED: Use VAE-specific evaluator
  num_eval: 30
  num_envs: 10
  eval_freq: 2000
  test_ret: 1.0
  vae_learning_rate: 0.001

  # Offline RL Trainer parameters
  target_update_freq: 50
  target_update_tau: 0.5
  # load checkpoint
  continue_training: false
